name:                bittrex-bot
version:             0.1.0.0
github:              "githubuser/simple"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/simple#readme>

default-extensions:
- OverloadedStrings
- DeriveGeneric
- DeriveAnyClass
- ScopedTypeVariables

dependencies:
- base >= 4.7 && < 5
- wreq == 0.5.*
- lens == 4.15.*
- aeson == 1.2.*
- lens-aeson == 1.0.*
- time == 1.8.*
- bytestring == 0.10.*
- Crypto == 4.2.*
- text == 1.2.*
- scientific == 0.3.*
- vector == 0.12.*
- Chart-cairo == 1.8.*
- Chart == 1.8.*
- timeit == 1.*
- deepseq == 1.4.*
- colour == 2.3.*
- containers == 0.5.*

library:
  source-dirs: src

executables:
  simple-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - bittrex-bot

tests:
  simple-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bittrex-bot
